version: '2'
services:
  sasawb:
    build: .
    image: docker.sas.com/kent/viya.awb:w47
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports: 
     - "80:80"
     - "5570:5570"
    volumes: 
     - /run
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
